import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"

const faqs = [
  {
    question: "How accurate are the AI-generated prompts?",
    answer:
      "Our AI achieves 99.5% accuracy in prompt generation using advanced computer vision and natural language processing. The quality depends on the input media clarity and resolution.",
  },
  {
    question: "What file formats are supported?",
    answer:
      "We support all major image formats (JPG, PNG, GIF, WebP) and video formats (MP4, AVI, MOV, WebM, WMV). Maximum file size is 100MB for images and 500MB for videos.",
  },
  {
    question: "Is my uploaded content secure?",
    answer:
      "Yes, absolutely. All uploaded files are processed securely and automatically deleted from our servers immediately after processing. We never store or share your content.",
  },
  {
    question: "Can I use the generated prompts commercially?",
    answer:
      "Yes, all prompts generated by VU3 PromGenerator can be used for commercial purposes without any restrictions. You own the rights to the generated content.",
  },
  {
    question: "How long does processing take?",
    answer:
      "Processing times vary by content type: Images typically take 2-5 seconds, videos take 10-30 seconds depending on length, and transcription takes 15-45 seconds.",
  },
  {
    question: "Do you offer API access?",
    answer:
      "Yes, we offer API access for developers and businesses. Contact our sales team for pricing and integration details.",
  },
]

export function FAQSection() {
  return (
    <section className="py-12 sm:py-16">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-8">
            <h2 className="text-2xl sm:text-3xl font-bold mb-3">
              Frequently Asked{" "}
              <span className="bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">Questions</span>
            </h2>
            <p className="text-sm text-muted-foreground">Find answers to common questions about VU3 PromGenerator</p>
          </div>

          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-left text-sm font-medium">{faq.question}</AccordionTrigger>
                <AccordionContent className="text-xs text-muted-foreground leading-relaxed">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  )
}
